# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-29 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailsub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250, null=True)),
                ('html_template', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('send_time', models.DateTimeField(blank=True, null=True)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailsub.Email')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailsub.Subscriber')),
            ],
        ),
        migrations.RemoveField(
            model_name='mail',
            name='subscriber_id',
        ),
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
