# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-29 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mailsub', '0002_auto_20221129_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmail',
            name='email_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
